version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=admin
    ports:
      - "1433:1433"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge